### ISSUE TITLE
Flink 1.2 Snapshot

### ISSUE THREAD

**Issue by nragon** [haoch/flink-siddhi#3]
Hello, 

Current release of flink-siddhi is using 1.2-SNAPSHOT flink right?
I'm getting the following error which seems to be a class from previous versions (until 1.1.4 this class was there):
```
Caused by: java.lang.NoClassDefFoundError: org/apache/flink/streaming/runtime/streamrecord/MultiplexingStreamRecordSerializer
        at org.apache.flink.contrib.siddhi.operator.SiddhiStreamOperator.createStreamRecordSerializer(SiddhiStreamOperator.java:46)
        at org.apache.flink.contrib.siddhi.operator.AbstractSiddhiOperator.registerStreamRecordSerializers(AbstractSiddhiOperator.java:120)
        at org.apache.flink.contrib.siddhi.operator.AbstractSiddhiOperator.<init>(AbstractSiddhiOperator.java:112)
        at org.apache.flink.contrib.siddhi.operator.SiddhiStreamOperator.<init>(SiddhiStreamOperator.java:40)
        at org.apache.flink.contrib.siddhi.utils.SiddhiStreamFactory.createDataStream(SiddhiStreamFactory.java:31)
        at org.apache.flink.contrib.siddhi.SiddhiStream$ExecutionSiddhiStream.returnsInternal(SiddhiStream.java:276)
        at org.apache.flink.contrib.siddhi.SiddhiStream$ExecutionSiddhiStream.returns(SiddhiStream.java:239)
```

Thank you

**Comment by haoch** [comment]
Hi @nragon a fixed version for stable dependency on `flink-1.3` is at branch [`flink_1.3`](https://github.com/haoch/flink-siddhi/tree/flink_1.3), made a more stable release based along with your fix as well, thanks very much for the contribution.
