### ISSUE TITLE
Bug:  ArrayOutofBoundsException thrown when using a Siddhi event stream of type DataStream<Map<String,Object>>> 

### ISSUE THREAD

**Issue by aagupta1** [haoch/flink-siddhi#33]
Stack trace - 

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at org.apache.flink.streaming.siddhi.schema.SiddhiStreamSchema.getStreamDefinition(SiddhiStreamSchema.java:49)
	at org.apache.flink.streaming.siddhi.schema.SiddhiStreamSchema.getStreamDefinitionExpression(SiddhiStreamSchema.java:64)
	at org.apache.flink.streaming.siddhi.operator.SiddhiOperatorContext.getAllEnrichedExecutionPlan(SiddhiOperatorContext.java:113)
	at org.apache.flink.streaming.siddhi.operator.AbstractSiddhiOperator.validate(AbstractSiddhiOperator.java:291)
	at org.apache.flink.streaming.siddhi.operator.AbstractSiddhiOperator.<init>(AbstractSiddhiOperator.java:178)
	at org.apache.flink.streaming.siddhi.operator.SiddhiStreamOperator.<init>(SiddhiStreamOperator.java:41)
	at org.apache.flink.streaming.siddhi.utils.SiddhiStreamFactory.createDataStream(SiddhiStreamFactory.java:31)
	at org.apache.flink.streaming.siddhi.SiddhiStream$ExecutionSiddhiStream.returnsInternal(SiddhiStream.java:331)
	at org.apache.flink.streaming.siddhi.SiddhiStream$ExecutionSiddhiStream.returnsInternal(SiddhiStream.java:327)
	at org.apache.flink.streaming.siddhi.SiddhiStream$ExecutionSiddhiStream.returnAsMap(SiddhiStream.java:287)

**Comment by haoch** [comment]
@aagupta1 Could you please share the test code?
