### ISSUE TITLE
A null pointer exception occurred, but I don't know why.

### ISSUE THREAD

**Issue by guanyufen123** [haoch/flink-siddhi#53]
details:
2019-10-11 13:42:26,364 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - Job  (ab76398582b1ffb8b58edb1a3bcd8dcd) switched from state RUNNING to FAILING.

java.lang.NullPointerException
	at org.apache.flink.streaming.siddhi.router.AddRouteOperator.processElement(AddRouteOperator.java:88)
	at org.apache.flink.streaming.runtime.io.StreamInputProcessor.processInput(StreamInputProcessor.java:202)
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask.run(OneInputStreamTask.java:105)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:300)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:745)
2019-10-11 13:42:26,377 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - Source: rocketmq-source -> Filter -> Flat Map -> Map (1/1) (232afd5328528608f6531fed6b4f1179) switched from RUNNING to CANCELING.

2019-10-11 13:42:26,384 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - Map (1/1) (a16760312d3a947f709749bfc727a4d8) switched from RUNNING to CANCELING.

2019-10-11 13:42:26,385 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - CEP: Unnamed (0ed54446-5e10-4431-9b49-e612a20c0a4d) -> Map -> Flat Map -> Sink: Unnamed (1/1) (f945babb746258fd0ede36a4550efbe7) switched from RUNNING to CANCELING.

2019-10-11 13:42:26,399 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - Map (1/1) (a16760312d3a947f709749bfc727a4d8) switched from CANCELING to CANCELED.

2019-10-11 13:42:26,403 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - CEP: Unnamed (0ed54446-5e10-4431-9b49-e612a20c0a4d) -> Map -> Flat Map -> Sink: Unnamed (1/1) (f945babb746258fd0ede36a4550efbe7) switched from CANCELING to CANCELED.

2019-10-11 13:42:26,518 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - Source: rocketmq-source -> Filter -> Flat Map -> Map (1/1) (232afd5328528608f6531fed6b4f1179) switched from CANCELING to CANCELED.

**Comment by haoch** [comment]
@guanyufen123 Could you please share your application code?

**Comment by guanyufen123** [comment]
> @guanyufen123 Could you please share your application code?

I think I know the reason. Thank you.

**Comment by haoch** [comment]
@guanyufen123 good to know that, please feel free to reach out to me if any more problems.

**Comment by guanyufen123** [comment]
ok,thanks

**Comment by guanyufen123** [comment]
> @guanyufen123 good to know that, please feel free to reach out to me if any more problems.

ok,thanks

**Comment by guanyufen123** [comment]
> @guanyufen123 good to know that, please feel free to reach out to me if any more problems.

Hello, if I use windows, should I set the parallelism to 1. I don't know if the parallelism is related to the final processing result of the window. Thank you

**Comment by LuckyBoyDE** [comment]
@guanyufen123 i have a similar stack trace. Can you maybe explain what your problem was?

**Comment by haoch** [comment]
@LuckyBoyDE What's your exception stack?

**Comment by LuckyBoyDE** [comment]
> @LuckyBoyDE What's your exception stack?

Well, actually i am not running flink-siddhi at all but an own flink application. Sadly i am not permitted to share stack traces or code.
I just have a very similar stack trace i am trying to debug and thought knowing what caused it in this case might help me. 

I am really sorry for hijacking this issue like this.

**Comment by SMART2016** [comment]
I am getting a similar issue while using control stream and has raised an issue separately , any help will be great:
https://github.com/haoch/flink-siddhi/issues/74

**Comment by madhurijain97** [comment]
Hi, can someone share their solution for this stacktrace. We are running into similar issue. Thank you
