### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by pavan91771** [haoch/flink-siddhi#63]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at org.apache.flink.streaming.siddhi.schema.SiddhiStreamSchema.getStreamDefinition(SiddhiStreamSchema.java:49)
	at org.apache.flink.streaming.siddhi.schema.SiddhiStreamSchema.getStreamDefinitionExpression(SiddhiStreamSchema.java:64)
	at org.apache.flink.streaming.siddhi.operator.SiddhiOperatorContext.getAllEnrichedExecutionPlan(SiddhiOperatorContext.java:113)
	at org.apache.flink.streaming.siddhi.operator.AbstractSiddhiOperator.validate(AbstractSiddhiOperator.java:295)
	at org.apache.flink.streaming.siddhi.operator.AbstractSiddhiOperator.<init>(AbstractSiddhiOperator.java:182)
	at org.apache.flink.streaming.siddhi.operator.SiddhiStreamOperator.<init>(SiddhiStreamOperator.java:42)
	at org.apache.flink.streaming.siddhi.utils.SiddhiStreamFactory.createDataStream(SiddhiStreamFactory.java:36)
	at org.apache.flink.streaming.siddhi.SiddhiStream$ExecutionSiddhiStream.returnsInternal(SiddhiStream.java:431)
	at org.apache.flink.streaming.siddhi.SiddhiStream$ExecutionSiddhiStream.returnsInternal(SiddhiStream.java:417)
	at org.apache.flink.streaming.siddhi.SiddhiStream$ExecutionSiddhiStream.returnAsRow(SiddhiStream.java:366)
	at org.apache.flink.streaming.siddhi.SiddhiStream$ExecutionSiddhiStream.returnAsRow(SiddhiStream.java:355)

**Comment by pavan91771** [comment]
I am taking the input from kafka

**Comment by pavan91771** [comment]
done
